pipeline.batch.size: 1000
config.reload.automatic: true
config.reload.interval: 10s
log.level: info
http.host: "0.0.0.0"
monitoring.enabled: false
# xpack.monitoring.elasticsearch.hosts: http://es01:9200
# xpack.monitoring.enabled: true
