---
- name: ELK Prerequisites
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  become: yes
  become_method: sudo

  tasks:

  - name: Add Elasticsearch GPG key.
    rpm_key:
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present

  - name: Add Elasticsearch repository.
    template:
      src: ./files/elastic/elasticsearch.repo.j2
      dest: /etc/yum.repos.d/elasticsearch.repo
      mode: 0644

  - name: update sysctl
    sysctl:
      name: vm.max_map_count
      value: 262144
      state: present
      reload: yes

