---
- name: Update ELK local checkout
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  become: yes
  become_method: sudo

  tasks:

  - command: git pull
    args:
      chdir: /opt/playbooks/elk-docker
