version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
      - xpack.monitoring.collection.enabled=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      # - ./elasticsearch/scripts:/usr/share/elasticsearch/scripts
    # entrypoint: /usr/share/elasticsearch/scripts/es-entrypoint.sh
    ports:
      - 9200:9200
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.0
    container_name: kibana
    hostname: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - XPACK_MONITORING_ENABLED=true
    restart: always
    ports:
      - 5601:5601
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.0
    container_name: logstash
    hostname: logstash
    environment:
      - "LS_JAVA_OPTS=-Xmx1g -Xms1g"
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      # - ./logstash/mordor-logs:/usr/share/logstash/mordor-logs
      # - ./logstash/scripts:/usr/share/logstash/scripts
    ports:
      - "5000-5100:5000-5100"
    restart: always
    # entrypoint: /usr/share/logstash/scripts/ls-entrypoint.sh
    networks:
      - elk

  #elastalert:
    #image: elastalert:latest
    #container_name: elastalert
    #restart: always
    #environment:
      #ES_HOST: es01
      #ES_PORT: 9200
    #networks:
      #- elk
  
  #domain_stats:
    #image: hasecuritysolutions/domain_stats
    #container_name: domain_stats
    #restart: always
    #networks:
      #- elk

volumes:
  esdata01:
    driver: local

networks:
  elk:
    name: elk
