logsources:
  windows-application:
    product: windows
    service: application
    index: logstash-winlogbeat-application-*
  windows-security:
    product: windows
    service: security
    index: logstash-winlogbeat-security-*
  windows-sysmon:
    product: windows
    service: sysmon
    index: logstash-winlogbeat-sysmon-*
  windows-system:
    product: windows
    service: system
    index: logstash-winlogbeat-system-*
  windows-wmi:
    product: windows
    service: wmi
    index: logstash-winlogbeat-wmiactivity-*
  windows-powershell:
    product: windows
    service: powershell
    index: logstash-winlogbeat-powershell-*
  windows-powershell-classic:
    product: windows
    service: powershell-classic
    index: logstash-winlogbeat-powershell-*
defaultindex: logstash-*
fieldmappings:
    AccessMask: object_access_mask_requested
    AccountName: event_data.TargetUserName
    AllowedToDelegateTo: user_attribute_allowed_todelegate
    AttributeLDAPDisplayName: dsobject_attribute_name
    AuditPolicyChanges: policy_changes
    AuthenticationPackageName: event_data.AuthenticationPackageName
    CallingProcessName: process_path
    CallTrace: process_call_trace
    CommandLine: event_data.CommandLine
    Company: event_data.Company
    ComputerName: computer_name
    Configuration:
        EventID=16: sysmon_configuration
    CurrentDirectory: event_data.CurrentDirectory
    Description: event_data.Description
    Destination:
        EventID=20: event_data.Destination
    DestinationHostname: event_data.DestinationHostname
    DestinationIp: event_data.DestinationIp
    DestinationIsIpv6: event_data.DestinationIsIpv6
    DestinationPort: event_data.DestinationPort
    DestinationPortName: event_data.DestinationPortName
    Details: 
        EventID=13: event_data.Details
    Device: device_name
    EngineVersion: event_data.ContextInfo
    EventID: event_id
    EventType: event_data.EventType
    EventNamespace:
        EventID=19: event_data.EventNamespace
    Filter:
        EventID=21: event_data.Filter
    FailureCode: ticket_failure_code
    FileName: event_data.FileName
    FileVersion: event_data.FileVersion
    GrantedAccess: process_granted_access
    GroupName: event_data.GroupName
    HiveName: event_data.HiveName
    HostVersion: powershell.host.version
    Image: event_data.Image
    ImageLoaded:
        EventID=6: event_data.ImageLoaded
        EventID=7: event_data.ImageLoaded
    Imphash: hash_imphash
    Initiated:
        EventID=3: network_initiated
    IntegrityLevel:
        EventID=1: event_data.IntegrityLevel
    LogonProcessName: event_data.LogonProcessName
    LogonType: event_data.LogonType
    MachineName: host.name
    Name:
        EventID=19: event_data.Name
        EventID=20: event_data.Name
    NewProcessName: event_data.NewProcessName
    NewName:
        EventID=14: registry_key_new_name
    ObjectClass: dsobject_class
    ObjectName: object_name
    ObjectType: object_type
    ObjectValueName: object_value_name
    Operation:
        EventID=19: event_data.Operation
        EventID=20: event_data.Operation
        EventID=21: event_data.Operation
    OperationType: object_operation_type
    ParentImage: event_data.ParentImage
    PasswordLastSet: user_attribute_password_lastset
    Path: process_path
    ParentCommandLine: event_data.ParentCommandLine
    PipeName: pipe_name
    ProcessName: process_path
    ProcesssCommandLine: event_data.CommandLine
    Product: event_data.Product
    Properties: object_properties
    Protocol:
        EventID=3: event_data.Protocol
    Query:
        EventID=19: event_data.Query
    RelativeTargetName: share_relative_target_name
    SchemaVersion:
        EventID=4: sysmon_schema_version
    ServiceFileName: event_data.ServiceFileName
    ServiceName: event_data.ServiceName
    ShareName: event_data.ShareName
    Signature: event_data.Signature
    SignatureStatus: signature_status
    Signed: signed
    Source: event_data.Source
    SourceHostname: event_data.SourceHostname
    SourceImage: event_data.SourceImage
    SourcePort: event_data.SourcePort
    SourcePortName: event_data.SourcePortName
    StartAddress: thread_start_address
    StartFunction: thread_start_function
    StartModule: thread_start_module
    Status: event_status
    State:
        EventID=4: service_state
        EventID=16: sysmon_configuration_state
    SubjectUserName: 
        EventID=4624: user_reporter_name
        EventId=4648: user_name
        EventID=5140: user_name
    TargetFilename: event_data.TargetFilename
    TargetImage: event_data.TargetImage
    TargetProcessAddress: event_data.TargetProcessAddress
    TargetObject: event_data.TargetObject
    TaskName: event_data.TaskName
    TicketEncryptionType: event_data.TicketEncryptionType
    TicketOptions: event_data.TicketOptions
    Type:
        EventID=20: event_data.Type
    User: user_account
    UserName: user_name
    Version:
        EventID=4: sysmon_version
    Workstation: src_host_name
    WorkstationName: event_data.WorkstationName
